services:
  web:
    build: .
    container_name: habitats_web
    ports:
      - "8000:8000"
    # Montamos el c√≥digo para ver cambios sin rebuild
    volumes:
      - ./habitats:/app/habitats
    environment:
      DJANGO_DEBUG: "True"
