services:
  - type: web
    name: habitats-espaciales
    env: docker
    plan: free
    region: oregon
    rootDir: habitats
    numInstances: 1
    envVars:
      - key: DJANGO_DEBUG
        value: "True"
